name: CI

on:
  pull_request:
    branches: ["dev"]

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start and Test Server
        run: |
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
